name: Email Reservation Processor

on:
  schedule:
    - cron: '0 */23 * * *'  # Runs every 23 hours
  workflow_dispatch:  # Allows manual triggering

jobs:
  process_emails:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install playwright
        playwright install chromium
    
    - name: Check Playwright installation
      run: |
        python -c "import playwright; print('Playwright package imported successfully')"
        playwright --version
        python -m playwright --version
        python -c "from playwright.sync_api import sync_playwright; print('Playwright sync API imported successfully')"
        python -c "from playwright.sync_api import sync_playwright; with sync_playwright() as p: print(f'Chromium version: {p.chromium.version}')"
  
    - name: Run email processor
      env:
        EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        ERROR_NOTIFICATION_EMAIL: ${{ secrets.ERROR_NOTIFICATION_EMAIL }}
        IMAP_SERVER: ${{ secrets.IMAP_SERVER }}
        IMAP_PORT: ${{ secrets.IMAP_PORT }}
      run: python email_processor.py
