name: Email Reservation Processor

on:
  schedule:
    - cron: '0 */23 * * *'  # Runs every 23 hours
  workflow_dispatch:  # Allows manual triggering

jobs:
  process_emails:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Check Python environment
      run: |
        python --version
        pip list

    - name: Verify IMAP connection
      run: |
        echo "Verifying IMAP connection:"
        nc -zv mail.kokoonvolos.gr 993 || echo "IMAP port is not accessible"
    
    - name: Run email processor
      env:
        EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      run: python email_processor.py

    - name: Check for script errors
      if: failure()
      run: |
        echo "The email processor script failed. Please check the logs for more information."
