name: Email Reservation Processor

on:
  schedule:
    - cron: '0 */23 * * *'  # Runs every 23 hours
  workflow_dispatch:  # Allows manual triggering

jobs:
  process_emails:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python -m spacy download en_core_web_sm
        playwright install chromium
    
    - name: Run email processor
      env:
        EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
        STAFF_EMAIL: ${{ secrets.STAFF_EMAIL }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        ERROR_NOTIFICATION_EMAIL: ${{ secrets.ERROR_NOTIFICATION_EMAIL }}
        IMAP_SERVER: ${{ secrets.IMAP_SERVER }}
        IMAP_PORT: ${{ secrets.IMAP_PORT }}
        EXCHANGERATE_API_KEY: ${{ secrets.EXCHANGERATE_API_KEY }}
      run: python email_processor.py
